/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.penjualanmakanan.view;

import com.penjualanmakanan.controller.DetailTransaksiController;
import java.util.ArrayList;
import java.util.List;
import com.penjualanmakanan.controller.TransaksiController;
import com.penjualanmakanan.model.Transaksi;
import com.penjualanmakanan.util.FormatRupiah;
import com.penjualanmakanan.util.FormatTanggal;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

class Process extends Thread {
    TransaksiView transaksiView;

    public Process(TransaksiView v) {
        this.transaksiView = v;
    }

    @Override
    public void run() {
        while (true) {
            transaksiView.bindingTabelTransaksi();
            
            try {
                Thread.sleep(5000);
            } catch (InterruptedException ex) {
                Logger.getLogger(Process.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
}

public class TransaksiView extends javax.swing.JFrame {
    
    List<Transaksi> listTransaksi = new ArrayList<>();
    
    TransaksiController transaksiController = new TransaksiController();
    DetailTransaksiController detailTransaksiController = new DetailTransaksiController();
    
    FormatRupiah formatRupiah = new FormatRupiah();
    FormatTanggal formatTanggal = new FormatTanggal();
    
    /**
     * Creates new form Transaksi
     */
    public TransaksiView() {
        initComponents();
        initFormValue();
        bindingTabelTransaksi();
    }
    
    public void initFormValue() {
        Id_Transaksi.setText(transaksiController.getMaxIdTransaksi());
        Tanggal_Transaksi.setText(formatTanggal.getValue(new Date(), "dd-MM-yyyy"));
    }
    
    public void bindingTabelTransaksi() {
        listTransaksi = new TransaksiController().getAllTransaksi();
        
        Object [][] obj = new Object[listTransaksi.size()][5];
        
        for (int i = 0; i < listTransaksi.size();i++){
            obj[i][0] = (i+1) + ".";
            obj[i][1] = listTransaksi.get(i).getId();
            obj[i][2] = listTransaksi.get(i).getTglTransaksi();
            obj[i][3] = String.valueOf(detailTransaksiController.getTotalBarangByIdTransaksi(listTransaksi.get(i).getId()));
            obj[i][4] = formatRupiah.kurensi(detailTransaksiController.getTotalHargaByIdTransaksi(listTransaksi.get(i).getId()));
        }
        
        Tabel_Transaksi.setModel(
            new javax.swing.table.DefaultTableModel(
                obj,
                new String [] {
                    "No.","ID Transaksi", "Tanggal Transaksi", "Total Barang", "Total Harga"
                }
            )
            {
                boolean[] canEdit = new boolean[]{
                    false, false, false, false, false
                };

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit[columnIndex];
                }
            }
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Id_Transaksi = new javax.swing.JTextField();
        Tanggal_Transaksi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Pilihan_Barang = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        Jumlah_Barang = new javax.swing.JTextField();
        Button_Tambah = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Daftar_Barang = new javax.swing.JTextArea();
        Button_Simpan = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Tabel_Transaksi = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        Kembali = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID Transaksi");

        jLabel2.setText("Tanggal");

        Id_Transaksi.setEditable(false);
        Id_Transaksi.setBackground(new java.awt.Color(230, 230, 230));
        Id_Transaksi.setEnabled(false);
        Id_Transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Id_TransaksiMouseClicked(evt);
            }
        });
        Id_Transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Id_TransaksiActionPerformed(evt);
            }
        });

        Tanggal_Transaksi.setEditable(false);
        Tanggal_Transaksi.setBackground(new java.awt.Color(230, 230, 230));
        Tanggal_Transaksi.setEnabled(false);
        Tanggal_Transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tanggal_TransaksiActionPerformed(evt);
            }
        });

        jLabel3.setText("Barang");

        Pilihan_Barang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Pilihan_Barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pilihan_BarangActionPerformed(evt);
            }
        });

        jLabel4.setText("Jumlah");

        Jumlah_Barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jumlah_BarangActionPerformed(evt);
            }
        });

        Button_Tambah.setText("Tambah");
        Button_Tambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_TambahMouseClicked(evt);
            }
        });
        Button_Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_TambahActionPerformed(evt);
            }
        });

        jLabel5.setText("Daftar Barang");

        Daftar_Barang.setColumns(20);
        Daftar_Barang.setRows(5);
        jScrollPane1.setViewportView(Daftar_Barang);

        Button_Simpan.setText("Simpan");

        jLabel6.setText("Tabel Transaksi");

        Tabel_Transaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(Tabel_Transaksi);

        jLabel7.setText("Beranda >> Transaksi");

        Kembali.setText("Kembali");
        Kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Button_Simpan))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addGap(31, 31, 31))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Tanggal_Transaksi)
                                    .addComponent(Id_Transaksi)
                                    .addComponent(Pilihan_Barang, 0, 95, Short.MAX_VALUE))
                                .addGap(24, 24, 24)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Jumlah_Barang, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(Button_Tambah))
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(Kembali))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Id_Transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tanggal_Transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Pilihan_Barang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(Jumlah_Barang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_Tambah))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_Simpan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Kembali)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Id_TransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Id_TransaksiActionPerformed
       
    }//GEN-LAST:event_Id_TransaksiActionPerformed

    private void Jumlah_BarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jumlah_BarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jumlah_BarangActionPerformed

    private void Pilihan_BarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pilihan_BarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pilihan_BarangActionPerformed

    private void Button_TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_TambahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_TambahActionPerformed

    private void Tanggal_TransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tanggal_TransaksiActionPerformed
        
    }//GEN-LAST:event_Tanggal_TransaksiActionPerformed

    private void Button_TambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_TambahMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_TambahMouseClicked

    private void Id_TransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Id_TransaksiMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Id_TransaksiMouseClicked

    private void KembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KembaliActionPerformed
        BerandaView beranda = new BerandaView();
        beranda.setVisible(true);
        dispose();
    }//GEN-LAST:event_KembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransaksiView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Simpan;
    private javax.swing.JButton Button_Tambah;
    private javax.swing.JTextArea Daftar_Barang;
    private javax.swing.JTextField Id_Transaksi;
    private javax.swing.JTextField Jumlah_Barang;
    private javax.swing.JButton Kembali;
    private javax.swing.JComboBox<String> Pilihan_Barang;
    private javax.swing.JTable Tabel_Transaksi;
    private javax.swing.JTextField Tanggal_Transaksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
